name: Weekly URL Checker

on:

  schedule:
    # 每星期日 UTC 00:00
    # 台灣時間星期日上午08:00
    - cron: '0 0 * * 0'

  workflow_dispatch:

jobs:

  check:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout

      uses: actions/checkout@v4

    - name: Setup Python

      uses: actions/setup-python@v5

      with:

        python-version: "3.11"

    - name: Install packages

      run: |

        pip install -r requirements.txt

    - name: Run checker

      run: |

        python check_urls.py

    - name: Commit result

      run: |

        git config --global user.name github-actions

        git config --global user.email github-actions@github.com

        git add .

        git diff --cached --quiet || git commit -m "Weekly Update"

        git push
